AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SourceDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: source-db
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: Password123!
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      PubliclyAccessible: true
      BackupRetentionPeriod: 1

      